In [176]:
import pandas as pd
import numpy as np

In [177]:
df = pd.read_excel("./pop_delta.xlsx")
df.columns = df.iloc[1]
df = df.iloc[3:]
df = df.dropna(how='all').reset_index(drop=True)
df = df.rename(columns={'Sơ bộ 2022': '2022'})
df.columns = df.columns.fillna("Region")
col_names = []
for col in df.columns:
    try: 
        col_names.append(str(int(col)))
    except ValueError:
        col_names.append(str(col))
        
df.columns = col_names
df.head()

non_province = ["CẢ NƯỚC", "Đồng bằng sông Hồng", "Trung du và miền núi phía Bắc", "Bắc Trung Bộ và Duyên hải miền Trung", "Đông Nam Bộ", "Đồng bằng sông Cửu Long"]
province = [r for r in df["Region"] if r not in non_province]

df = df[df["Region"].isin(province)].reset_index(drop=True)
df['Region'] = df['Region'].str.replace("oà", "òa")
df['Region'] = df['Region'].str.replace("oá", "óa")
for col in df.columns:
    if col != "Region":
        df[col] = df[col].replace("..", np.nan).astype(float)
        
def add_prefix(cn):
    try: 
        year = int(cn)
        if True:
            return f"y_{year}"
    except ValueError:
        pass
    return cn

df = df.rename(columns=add_prefix)
df = df[df['Region'] != "Hà Tây"]
df.head()

,Region,y_2005,y_2007,y_2008,y_2009,y_2010,y_2011,y_2012,y_2013,y_2014,y_2015,y_2016,y_2017,y_2018,y_2019,y_2020,y_2021,y_2022
0,Hà Nội,2.02,1.37,NaN,1.41,2.50,1.93,1.54,1.63,1.70,2.03,2.11,1.99,2.23,2.27,1.89,1.02,1.26
2,Vĩnh Phúc,1.03,0.69,NaN,0.66,0.72,0.38,1.09,0.68,1.22,1.26,1.45,1.54,1.36,1.45,1.42,1.75,0.49
3,Bắc Ninh,0.80,0.95,0.87,0.82,1.73,1.84,2.10,2.06,2.08,3.52,3.23,3.17,3.05,3.08,2.94,3.09,1.73
4,Quảng Ninh,1.33,1.19,1.12,0.97,0.97,0.93,0.83,0.82,1.01,1.13,1.58,1.90,1.46,1.61,0.96,0.99,0.89
5,Hải Dương,0.30,0.30,0.36,0.35,0.56,0.78,0.69,0.58,0.65,0.95,1.11,0.97,1.46,1.02,1.05,1.04,0.52

In [178]:
df[df['Region'] == "Đắk Nông"]

,Region,y_2005,y_2007,y_2008,y_2009,y_2010,y_2011,y_2012,y_2013,y_2014,y_2015,y_2016,y_2017,y_2018,y_2019,y_2020,y_2021,y_2022
45,Đắk Nông,4.99,3.73,3.72,3.51,2.61,3.13,3.3,3.42,2.91,2.75,2.4,1.76,1.74,1.69,1.93,4.16,0.92

In [179]:
vndf = pd.read_csv("./Vietnam_properties_f.csv", sep=";", encoding="UTF-8")

#df_list = []

for col in df.columns[1:]:
    t_df = vndf.copy()
    t_df = pd.merge(t_df, df[["Region", col]], how='left', left_on='name', right_on='Region')
    t_df = t_df.drop(columns=["Region"], axis=1)
    t_df.to_csv(f"./popdelta_geoready/{col[2:]}.csv", sep=",", encoding="UTF-8", compression=None)


#t_df[t_df["name"] != "Đắk Nông"]