In [28]:
import pandas as pd
from useful_func import *

ex = pd.ExcelFile("./raw/indepth_pop.xlsx")
df = pd.read_excel(ex, "Bieu 12")
df.columns = df.iloc[1]
df = df.iloc[3:]
df = df.dropna(how='all').reset_index(drop=True)
df = df.rename(columns={'Sơ bộ 2022': '2022'})
df.columns = df.columns.fillna("Region")
col_names = []
for col in df.columns:
    try: 
        col_names.append(str(int(col)))
    except ValueError:
        col_names.append(str(col))
        
df.columns = col_names
df.head()

non_province = ["CẢ NƯỚC", "Tỉnh, thành phố", "Đồng bằng sông Hồng", "Trung du và miền núi phía Bắc", "Trung du miền núi phía Bắc", "Bắc Trung Bộ và Duyên hải miền Trung", "Đông Nam Bộ", "Đồng bằng sông Cửu Long", "Vùng kinh tế - xã hội"]
province = [r for r in df["Region"] if r not in non_province]
df = df[df["Region"].isin(province)].reset_index(drop=True)
df.columns = ["Region", "total", "male", "female"]

In [29]:
df.head()

       Region      total       male     female
0   Thành thị  26.400426  28.066386  24.768568
1   Nông thôn  24.479381  26.675179   22.06341
2  Tây Nguyên  23.921971  25.890481  21.773196
3      Hà Nội  25.735597  27.347251  24.152807
4    Hà Giang  21.384381  22.828077  19.701417

VIETNAM .shp file by district

In [31]:
import geopandas as gpd
dist = gpd.read_file("./gmvn10/polbnda.shp")
dist.head(10)

,f_code,f_code_des,coc,laa,nam,soc,tile_id,fac_id,geometry
0,FA001,Administrative Area,VNM,YEN MINH,HA GIANG,VNM,1,2,"POLYGON Z ((104.94386 23.19103 0, 104.94897 23..."
1,FA001,Administrative Area,VNM,QUAN BA,HA GIANG,VNM,1,3,"POLYGON Z ((105 23.16639 0, 105 22.99819 0, 10..."
2,FA001,Administrative Area,VNM,VI XUYEN,HA GIANG,VNM,1,4,"POLYGON Z ((104.83897 22.98394 0, 104.85587 22..."
3,FA001,Administrative Area,VNM,HOANG SU PHI,HA GIANG,VNM,1,5,"POLYGON Z ((104.60099 22.81581 0, 104.60945 22..."
4,FA001,Administrative Area,VNM,HA GIANG,HA GIANG,VNM,1,6,"POLYGON Z ((105 22.87099 0, 105 22.78086 0, 10..."
5,FA001,Administrative Area,VNM,MUONG KHUONG,LAO CAI,VNM,1,7,"POLYGON Z ((104.27446 22.83867 0, 104.27006 22..."
6,FA001,Administrative Area,VNM,Si Ma Cai,LAO CAI,VNM,1,8,"POLYGON Z ((104.26798 22.74313 0, 104.27364 22..."
7,FA001,Administrative Area,VNM,XIN MAN,HA GIANG,VNM,1,9,"POLYGON Z ((104.33732 22.70739 0, 104.34689 22..."
8,FA001,Administrative Area,VNM,HA GIANG,HA GIANG,VNM,1,10,"POLYGON Z ((105 22.74449 0, 105 22.67977 0, 10..."
9,FA001,Administrative Area,VNM,PHONG THO,LAI CHAU,VNM,1,11,"POLYGON Z ((103.29359 22.77117 0, 103.29433 22..."

In [38]:
x = dist.laa.unique()
len(x)

620